[2015-11-30 16:54:05] request.INFO: Matched route "app_users_in" (parameters: "_controller": "App\AppBundle\Controller\DefaultController::usersAction", "in": "true", "_route": "app_users_in") [] []
[2015-11-30 16:54:07] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42000] [1226] User 'u575559702_user' has exceeded the 'max_user_connections' resource (current value: 3)" at /home/u575559702/public_html/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 40 {"exception":"[object] (PDOException: SQLSTATE[42000] [1226] User 'u575559702_user' has exceeded the 'max_user_connections' resource (current value: 3) at /home/u575559702/public_html/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)"} []
[2015-12-11 14:08:31] request.INFO: Matched route "app_gdc_war_info" (parameters: "_controller": "App\AppBundle\Controller\GdcController::warInfoAction", "id": "31", "_route": "app_gdc_war_info") [] []
[2015-12-11 14:08:36] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42000] [1226] User 'u575559702_user' has exceeded the 'max_user_connections' resource (current value: 3)" at /home/u575559702/public_html/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 40 {"exception":"[object] (PDOException: SQLSTATE[42000] [1226] User 'u575559702_user' has exceeded the 'max_user_connections' resource (current value: 3) at /home/u575559702/public_html/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:40)"} []
[2015-12-11 19:08:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /gdc/stats" (from "http://winnick.esy.es/")" at /home/u575559702/public_html/api/app/cache/prod/classes.php line 1977 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /gdc/stats\" (from \"http://winnick.esy.es/\") at /home/u575559702/public_html/api/app/cache/prod/classes.php:1977, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at /home/u575559702/public_html/api/app/cache/prod/appProdUrlMatcher.php:92)"} []
[2015-12-11 19:08:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /gdc/statsUsers" (from "http://winnick.esy.es/")" at /home/u575559702/public_html/api/app/cache/prod/classes.php line 1977 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /gdc/statsUsers\" (from \"http://winnick.esy.es/\") at /home/u575559702/public_html/api/app/cache/prod/classes.php:1977, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at /home/u575559702/public_html/api/app/cache/prod/appProdUrlMatcher.php:92)"} []
